### ISSUE TITLE
mv: cannot stat 'agents.php?download=1': No such file or directory python3: can't open file 'hashtopolis.zip': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by manves** [JoelGMSec/Cloudtopolis#6] opened 2022-04-08 01:18 UTC
Hello, I followed step one. I setup Cloud shell, I then did the collab script and when it downloads and runs the agent it gets an error 

[i] Download and run agent..
mv: cannot stat 'agents.php?download=1': No such file or directory
python3: can't open file 'hashtopolis.zip': [Errno 2] No such file or directory

I think something is happening with the download itself

**Comment by ashishgajjar90** [comment] 2022-04-12 08:35
Hi,

I'm also facing the same issue. Is there something wrong with the download?

**Comment by JoelGMSec** [comment] 2022-04-12 10:00
Hi!

I just added an exception to Google authentication.

Basically, in some (totally random) cases authentication works normally without problems. In other cases, a popup appears asking for GCloud access.

The problem is that access through the popup is useless, so it is necessary to authenticate through a console (from any operating system) and execute the command that appears below the red warning.

<img width="581" alt="chrome_eAQ3Dgbmjz" src="https://user-images.githubusercontent.com/34335312/162932422-45a71734-4a94-4591-bc67-c7b5a6130757.png">

It is essential to have Google Cloud SDK installed to be able to execute this process.

If you use Windows and don't want to complicate things, installing the Cloudtopolis Server from PowerShell means that you don't have to perform any manual steps.

The command, from an administrator console, would be as follows:
```iwr -useb https://raw.githubusercontent.com/JoelGMSec/Cloudtopolis/master/Resources/Server/Cloudtopolis_Server.ps1 | iex```

This should work without any problems.


Regards!

**Comment by ashishgajjar90** [comment] 2022-04-12 11:39
Thanks for your quick response. I setup the entire environment again and still doesn't seem to have changed anything :(

![image](https://user-images.githubusercontent.com/40457769/162951825-093650a7-007e-4f69-a73c-6b6dc38ca3e3.png)

**Comment by ashishgajjar90** [comment] 2022-04-12 11:47
Hi! Thanks for the quick reply. I have tried again with the new steps mentioned, but I am still running into the issue below:

![image](https://user-images.githubusercontent.com/40457769/162953179-9aada8ad-132e-4571-8ca4-573e0f7135eb.png)

**Comment by JoelGMSec** [comment] 2022-04-12 14:59
I found the bug and got it to work, but it seems that now the API that allowed code to be executed via SSH is disabled by default and works half the time.

<img width="478" alt="chrome_Goqy4kKUfk" src="https://user-images.githubusercontent.com/34335312/162989582-16a9276f-1425-462b-9f71-8c9f619ec008.png">

It might take me some more time to solve this part, I'll try to get to it as soon as possible.

Thanks for your feedback,


Regards!

**Comment by ashishgajjar90** [comment] 2022-04-12 19:37
Thanks! I'll give it a try again and hopefully I'm able to get it to work
while you work on trying to apply a more permanent solution! :D

Thanks & Regards

Ashish Gajjar

**Comment by ashishgajjar90** [comment] 2022-04-12 19:37
Thanks for the update! I'll give it a shot again and hopefully I'm 50% successful in getting it to work hehe! Hope you're able to find a more permanent fix to this soon! :D

**Comment by JoelGMSec** [comment] 2022-04-20 08:01
Hi again,

Due to the current difficulties with Google's authentication system and the problems with executing commands via SSH (because the API is now disabled by default), I have decided to use a third party to temporarily fix the problem.

It's not the most elegant solution, nor is it my preferred option, but for now it works fine. Basically, there is now a new concept, the "link" to be copied from Cloud Shell and pasted into Colab under the voucher.

<img width="960" alt="chrome_ORAri3JLV4" src="https://user-images.githubusercontent.com/34335312/164179045-ff4a1d16-efb1-4c83-b6ab-03dfdd4ff06f.png">

<img width="960" alt="chrome_pNGil9LTze" src="https://user-images.githubusercontent.com/34335312/164179243-1d1b63e3-9a7e-4827-a939-4285306e98b4.png">

The only drawback is that execution times through this system are somewhat shorter. To generate a new link, it is only necessary to re-launch the script and re-register the Colab agent.

The good thing is that the registration is now much faster, and for short tasks it is more than enough. If you need more time, it is advisable to use a VPS (or your own computer via NAT) and use Colab Pro accounts.

I hope this helps,


Regards!

**Comment by manves** [comment] 2022-04-24 23:22
Thank you for the reply however, I still get the same error. I tried on a new google account and I also tried vps mode. I am not really sure what I am doing wrong

**Comment by JoelGMSec** [comment] 2022-04-29 08:19
Hi manves!

Honestly, I don't know what could be happening. I have been using Cloudtopolis for all these days (after the update) and I haven't had any problems with it.

In any case, I'm closing this thread (since the bug with Google authentication is now solved, at least temporarily).

If after reviewing the guide and trying again you still have a problem, open another thread with the step-by-step and we'll take a closer look.

Regards!

**Closed as completed by JoelGMSec** 2022-04-29 08:19 UTC
